#https://docs.docker.com/compose/
#image: nombre de la image construida y la version con la cual se tageo.
#ports: puertos forwardeados por docker desde su red a nuestra red. ¿Queres saber mas sobre container networking? https://docs.docker.com/config/containers/container-networking/
#volumes: copia los datos de nuestro support al container final con permisos read-only, para que nuestra app pueda accederlos.
#en caso de trabajar con snapshots, puede utilizar los volumenes para inyectar el snapshot en el container asi no tienen que generarlos cada vez que levanten el container
version: "3"
services:
  nebula-java-docker-example:
    image: "java-template:${TAG_VERSION}"
    ports:
      - "9290:9290"
      - "9800:9800"
    volumes:
      - ./configuration/nebula/${ENVIRONMENT}/:/service/config/:rw
      - ./configuration/nebula/${ENVIRONMENT}/:/service/secrets/:ro
